name: steady-2d-heat
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - numpy
  - pandas
  - mpi4py
  - petsc4py
  - fenics-basix
  - fenics-ufl
  - fenics-dolfinx
  - pyvista
  - pip:
      - -e .
